name: CD

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
    branches:
      - main

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: exit 0
  publish:
    name: Publish on Docker Hub
    needs:
      - ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Build image
        run: docker image build -t gabrielrufino/node-proxy:latest -t gabrielrufino/node-proxy:$(npm pkg get version | sed 's/"//g') .
      - name: Log in docker hub
        run: docker login -u gabrielrufino -p ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Publish image
        run: docker image push -a gabrielrufino/node-proxy
      - name: Set docker hub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: gabrielrufino
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: gabrielrufino/node-proxy
