name: Node Proxy CD

on:
  workflow_run:
    workflows: ['Node Proxy CI']
    types:
      - completed
    branches:
      - main

jobs:
  publish:
    name: Publish on Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker image build -t gabrielrufino/node-prox -t gabrielrufino/node-proxy:$(npm pkg get version | sed 's/"//g') .
      - name: Log in docker hub
        run: docker login -u gabrielrufino -p ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Publish image
        run: docker image push -a gabrielrufino/node-proxy
